language: bash

env:
  SCALA_VERSION: "2.12"
  KAFKA_VERSION: "1.0.0"

services:
- docker

before_install:
- docker build --no-cache -t engapa/kafka:${SCALA_VERSION}-${KAFKA_VERSION} .

install:
- docker run -it -d --name kafka -e "DEBUG_SETUP=true" engapa/kafka:${SCALA_VERSION}-${KAFKA_VERSION}

script:
- docker exec -it kafka kafka_server_status.sh

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push engapa/kafka:${SCALA_VERSION}-${KAFKA_VERSION}
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker build --no-cache -t engapa/kafka:latest .;
    docker push engapa/kafka:latest;
  fi

after_script:
- docker stop kafka
- docker rm kafka
