language: bash

env:
  SCALA_VERSION: "2.12"
  KAFKA_VERSION: "0.11.0.1"

services:
  - docker

before_install:
- docker build --rm=true -t engapa/kafka:${SCALA_VERSION}-${KAFKA_VERSION} .

install:
- docker run -it -d --name kafka -e "DEBUG_SETUP=true" engapa/kafka:${SCALA_VERSION}-${KAFKA_VERSION}

script:
- docker exec -it kafka kafka_server_status.sh

after_script:
- docker stop kafka
- docker rm kafka