language: bash
sudo: required
dist: trusty

env:
  SCALA_VERSION: "2.12"
  KAFKA_VERSION: "1.0.0"
  MINIKUBE_VERSION: "v0.24.1"
  KUBE_VERSION: "v1.8.0"

services:
- docker

before_install:
# Download and install latest stable version of kubectl
- |
  docker build --no-cache -t engapa/kafka:${SCALA_VERSION}-${KAFKA_VERSION}-dev${TAVIS_BUILD} \
   -t engapa/kafka:${SCALA_VERSION}-${KAFKA_VERSION} .
# export KUBE_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBE_VERSION/bin/linux/amd64/kubectl
# Download minikube.
- >
  curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBE_VERSION/minikube-linux-amd64 &&
   chmod +x minikube &&
   sudo mv minikube /usr/local/bin/

install:
- docker run -it -d --name kafka -e "DEBUG_SETUP=true" engapa/kafka:${SCALA_VERSION}-${KAFKA_VERSION}-dev${TAVIS_BUILD}
- chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- minikube version
- sudo minikube start --vm-driver=none --kubernetes-version=$KUBE_VERSION
- sudo minikube update-context
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
- kubectl version

after_install:
- docker exec -it kafka kafka_server_status.sh
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push engapa/kafka:${SCALA_VERSION}-${KAFKA_VERSION}-dev${TAVIS_BUILD}

before_script:
- kubectl cluster-info

script:
- sed -i.bak "s/${SCALA_VERSION}-${KAFKA_VERSION}/${SCALA_VERSION}-${KAFKA_VERSION}-dev${TAVIS_BUILD}/g" k8s/kafka.yaml
- kubectl create -f k8s/kafka.yaml
- if [[ $(kubectl get pods --field-selector=status.phase==Running | grep kafka | wc -l) -gt 0 ]]; then exit 1; fi

after_success:
- docker push engapa/kafka:${SCALA_VERSION}-${KAFKA_VERSION}
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build --no-cache -t engapa/kafka:latest;
    docker push engapa/kafka:latest;
  fi

after_script:
- docker rm -f kafka
- minikube delete