apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kafka
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: engapa/kafka:2.12-0.11.0.0
        ports:
        - containerPort: 9092
          name: server
        env:
        - name: KAFKA_REPLICAS
          value: "2"
        - name: KAFKA_ZK_LOCAL
          value: "false"
        - name: SERVER_zookeeper_connect
          value: "zk-0.zk-svc:2181,zk-1.zk-svc:2181,zk-2.zk-svc:2181"
        livenessProbe:
          exec:
            command:
            - kafka_server_status.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5