apiVersion: v1
kind: Service
metadata:
  name: zk-svc
  labels:
    app: zk
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 2181
    name: zkclient
  - port: 2888
    name: zkserver
  - port: 3888
    name: zkleader
  clusterIP: None
  selector:
    app: zk
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zk
spec:
  serviceName: zk-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zk
        imagePullPolicy: Always
        image: engapa/kafka:2.12-0.10.2.0
        ports:
        - containerPort: 2181
          name: zkclient
        - containerPort: 2888
          name: zkserver
        - containerPort: 3888
          name: zkleader
        env:
        - name: KAFKA_REPLICAS
          value: "3"
        command:
        - /bin/bash
        - -c
        - source kafka_env.sh && kafka_setup.sh && bin/zookeeper-server-start.sh config/zookeeper.properties
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kafka
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: engapa/kafka:2.12-0.10.2.0
        ports:
        - containerPort: 9092
          name: server
        env:
        - name: KAFKA_REPLICAS
          value: "2"
        - name: SERVER_zookeeper_connection_timeout_ms
          value: "30000"
        - name: KAFKA_ZK_LOCAL
          value: "false"
        - name: SERVER_zookeeper_connect
          value: "zk-0.zk-svc:2181,zk-1.zk-svc:2181,zk-2.zk-svc:2181"
        command:
        - /bin/bash
        - -c
        - source kafka_env.sh && kafka_setup.sh && kafka_server.sh start
        livenessProbe:
          exec:
            command:
            - kafka_server.sh
            - status
          initialDelaySeconds: 15
          timeoutSeconds: 5